# Generated by Django 4.0.5 on 2022-06-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentgroup_student_birthdate_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='sudents_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество студентов'),
        ),
    ]
