# Generated by Django 4.0.5 on 2022-06-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_options_studentgroup_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='surname',
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, choices=[('Ivanenko', 'Іваненко'), ('Petrenko', 'Петренко')], max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
